name: Update Visitor Count

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행

jobs:
  update-visitor-count:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get current visitor count from Glitch
        id: get_count
        run: |
          count=$(curl -s https://tricolor-real-thrill.glitch.me/count) # 서버 URL 수정 필요
          echo "count=${count}" >> $GITHUB_ENV

      - name: Update README with visitor count
        run: |
          sed -i "s/Visitor count: [0-9]*/Visitor count: ${count}/g" README.md
          git config --local user.email "your-email@example.com"
          git config --local user.name "your-username"
          git commit -am "Update visitor count to ${count}"
          git push
