name: Update Visitor Count

# 워크플로가 실행될 이벤트 설정
on:
  push:
    branches:
      - main  # main 브랜치로 푸시될 때마다 실행
  schedule:
    - cron: '0 9 * * *'  # 매일 오전 9시에 실행
  workflow_dispatch:  # Actions 탭에서 수동으로 실행 가능

jobs:
  update-visitor-count:
    runs-on: ubuntu-latest

    steps:
      # Glitch 서버로 방문자 수 증가 요청을 보내는 단계
      - name: Send request to Glitch server
        run: |
          curl -X GET https://tricolor-real-thrill.glitch.me/redirect
